### ISSUE TITLE
Custom Colors inconsistent on first change

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#660] opened 2021-01-14 03:38 UTC
Weird behavior with custom colors on message_view. When you first open a chat, and change a contacts color, the color doesn't change newly loaded messages. Scroll up in chat to see that the loaded messages are still using the old color. Fix is easy. You simply have to close the chat so that the color sticks. Small issue, but still.

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@Intellijence` in `#requests`.

**Comment by zlshames** [comment] 2021-06-16 22:21
Duplicate of: https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/723
Closing

**Closed by zlshames** 2021-06-16 22:21 UTC
Labels: Bot Created, Bug, Nightly
