### ISSUE TITLE
Jump to oldest unread

### ISSUE THREAD

**Issue by Bricktheworld** [BlueBubblesApp/BlueBubbles-Android-App#564] opened 2020-12-22 18:45 UTC
When receiving large numbers of new message, add option to jump to the oldest unread message

**Comment by zlshames** [comment] 2021-06-17 00:24
Duplicate of: https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/680
Closing, even though this is older

**Closed by zlshames** 2021-06-17 00:24 UTC
Labels: Backlog, Enhancement
