### ISSUE TITLE
[Material] Sent images don't have enough right padding

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1207] opened 2021-07-27 23:54 UTC
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-bugs`.

**Comment by tneotia** [comment] 2021-08-02 23:47
@zlshames can't reproduce this one either

**Comment by zlshames** [comment] 2021-08-02 23:49
Closing for now. I don't remember who brought it up. But if they do again, we can reopen or recreate the issue

**Closed by zlshames** 2021-08-02 23:49 UTC
Labels: Bot Created, Bug, Difficulty: Easy, UX, priority: high
