### ISSUE TITLE
when someone keeps an audio message, it shows as a blank

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#869] opened 2021-06-11 11:51 UTC
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-bugs`.

**Comment by zlshames** [comment] 2021-06-11 18:31
Can't reproduce this. Closing until we can consistently reproduce it

**Closed by zlshames** 2021-06-11 18:31 UTC
Labels: Bot Created
