### ISSUE TITLE
Voice messages are prompted send/discard twice after recording

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#829] opened 2021-04-28 22:16 UTC
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@Clamscrambler` in `#android-bugs`.

**Comment by zlshames** [comment] 2021-05-14 22:14
I can't reproduce this. Going to ask in Discord, but otherwise, might close it

**Comment by zlshames** [comment] 2021-06-15 01:04
Closing this until I either get more info or people get this more anecdotal-y

**Closed by zlshames** 2021-06-15 01:04 UTC
Labels: Bot Created
