### ISSUE TITLE
Crashes After QR Code Scan

### ISSUE THREAD

**Issue by pjpugliese** [BlueBubblesApp/BlueBubbles-Android-App#450] opened 2020-11-21 21:40 UTC
Not able to complete setup. Once the setup QR code is scanned the app crashes. Opening the app again immediately crashes it. The only way to get the app open again is to clear storage, force stop, and relaunch. Same issue loop.

**Comment by zlshames** [comment] 2020-11-21 21:49
Hey @pjpugliese, can you please do a full reinstall of the app, and install the nightly build: https://drive.google.com/file/d/1RLW6HSYGSVlXim53MHBxzW3FJDCzoDeH/view?usp=sharing

Currently, we are preparing to do a full beta release to the play store, and essentially go public. The version you have seems to be an old one. The only way to fix it is to install the newest version (from clean) via the link above

**Comment by pjpugliese** [comment] 2020-11-21 22:01
Thanks for the quick reply @zlshames! I uninstalled and re-installed using this link. I noticed some UI tweaks in the update, but the end result appears to be the same. I end up back on the "BlueBubbles keeps stopping" error until I clear out everything. Setup fails.

**Comment by zlshames** [comment] 2020-11-21 22:08
> Thanks for the quick reply @zlshames! I uninstalled and re-installed using this link. I noticed some UI tweaks in the update, but the end result appears to be the same. I end up back on the "BlueBubbles keeps stopping" error until I clear out everything. Setup fails.

So were you able to get it to sync with the server, and it crapped out somewhere else? Or is it still crashing after starting setup?

**Comment by pjpugliese** [comment] 2020-11-21 22:11
Crashes after the scan or manual input. Never get to the sync.

**Comment by zlshames** [comment] 2020-11-21 22:27
Can you please upload you server's log file? It's located on your Mac, at: `~/Library/Logs/bluebubbles-server/main.log`

**Comment by pjpugliese** [comment] 2020-11-21 22:30
Sure, but is there anything I need to strip out before posting?

**Comment by zlshames** [comment] 2020-11-21 23:02
> Sure, but what specific parts do you need? I see some personal details in the logs.

If you want, you can join the discord and DM it to us. That might be more private. The discord is on our website/wiki

**Comment by pjpugliese** [comment] 2020-11-22 03:28
I joined and will take a look there. Might also wait for the Play Store release if imminent. Thanks!

**Comment by Bricktheworld** [comment] 2020-11-22 10:10
Did this ever get fixed?

**Comment by pjpugliese** [comment] 2020-11-22 16:01
I installed 1.0 from the Play Store just now. That version crashes immediately upon opening.

**Comment by zlshames** [comment] 2020-11-22 16:12
> I installed 1.0 from the Play Store just now. That version crashes immediately upon opening.

Yeah, sorry about that. The build on the playstore was a mistake. We will be pulling it again.

**Comment by Bricktheworld** [comment] 2020-12-06 06:19
So another person encountered the same issue: their password was bluebubblespasswordbr%h and after changing it stopped crashing. Likely the issue is the percent sign

**Comment by zlshames** [comment] 2020-12-06 13:14
> So another person encountered the same issue: their password was bluebubblespasswordbr%h and after changing it stopped crashing. Likely the issue is the percent sign

It's due to the guidAuthKey being a URL parameter

**Comment by pjpugliese** [comment] 2020-12-06 14:39
That appears to have been the issue! 

My password also contained & and that appears to cause an issue on the getting chats screen. It got stuck there and kept saying disconnected from socket.

**Comment by zlshames** [comment] 2020-12-08 17:59
Closing this issue as it has not come up recently. Also, I already made changes to the android app to URI encode the guid. I also added URI decoding to the server (hasn't been released as of now)

**Closed by zlshames** 2020-12-08 17:59 UTC
Labels: Bug
