### ISSUE TITLE
Incoming messages aren't colored by Custom Avatar Color

### ISSUE THREAD

**Issue by SoPat712** [BlueBubblesApp/BlueBubbles-Android-App#723] opened 2021-02-01 22:56 UTC
and it doesnt recolor previous messages
you have to close the convo and reopen it for previous messages from the contact to get recolored

**Comment by zlshames** [comment] 2021-08-31 13:04
Moving this to the v1.5.0 release. Also setting it as medium as it should be easier with GetX. I think the issue here is that we use the properties for the Handle from the notification packet, and not one that's merged with the one we have in the DB. We have to properly merge the participants data with the database handles so that we don't revert to null for the color.

I know it's this issue because leaving and re-entering the chat fixes the issue. So the issue is with the data going from -> NewMessageManager.add -> MessageView.

We had a similar issue with chats, and having the mimetype being overriden by null. I wonder if this is similarly related

**Closed** 2021-09-01 03:42 UTC
Labels: Bug, UX, Difficulty: Medium
