### ISSUE TITLE
Support Android Auto

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#818] opened 2021-03-25 16:20 UTC
Check this guide out: https://developer.android.com/training/cars/messaging

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#general`.

**Comment by zlshames** [comment] 2021-07-21 01:41
This is actually really easy I think. Just read this: https://developer.android.com/training/cars/media/auto

Should be a matter of adding a meta tag

**Comment by romhacks** [comment] 2021-07-23 01:50
Unfortunately it seems like it's only that simple for media apps (music player, etc). Messaging apps need more stuff and flutter might not support auto as of now. https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/1149 is a duplicate of this issue but has some comments referencing this.

**Closed** 2021-07-24 20:58 UTC
Labels: Bot Created, Difficulty: Easy, Enhancement, priority: high
