### ISSUE TITLE
Fix shortcuts on launcher

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1227] opened 2021-07-31 21:33 UTC
You can't actually open the shortcut in BB

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#requests`.

**Comment by CSab6482** [comment] 2021-08-02 20:47
Dupe of #295?

**Comment by CSab6482** [comment] 2021-08-02 20:48
Dupe of #295? @tneotia

**Comment by tneotia** [comment] 2021-08-02 20:48
> Dupe of #295? @tneotia

Yes

**Closed by tneotia** 2021-08-02 20:48 UTC
Labels: Bot Created
