### ISSUE TITLE
image swipe gallery swipe direction is backwards

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1098] opened 2021-07-17 13:01 UTC
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#feedback`.

**Comment by CSab6482** [comment] 2021-07-17 16:34
Is this a dupe of #1086?

**Comment by tneotia** [comment] 2021-07-18 01:19
Yes but I think we should just change it rather than giving the option

**Comment by CSab6482** [comment] 2021-07-18 01:53
> Yes but I think we should just change it rather than giving the option

I personally think we should too, but I think some people are used to or prefer the other swipe option, so should it be toggleable?

**Comment by tneotia** [comment] 2021-07-18 13:04
I don't want to make *everything* a setting as I've said before - it just kinda clutters up stuff as we pile more and more on. I think a better solution is to show a toast message the first time the Fullscreen viewer is opened after the update to inform people the scrolling direction has changed. Obv it's just an opinion so if you think otherwise lmk

**Comment by CSab6482** [comment] 2021-07-18 18:18
I agree that User Experience and Conversation Settings are a bit cluttered. If this could be sneaked into attachment settings, I'd be all for it. However, I know sometimes making a feature modular is more trouble than it's worth, so I understand if it's just changed instead of made toggleable.

**Comment by tneotia** [comment] 2021-07-18 18:21
*sighs*

Alright fineeee csab, I'll add your feature in

:)

**Closed** 2021-07-20 00:28 UTC
Labels: Bot Created
