### ISSUE TITLE
[Feature Request] Temporarily Mute a Chat

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#1410] opened 2021-08-24 20:47 UTC
Related: #442 

I don't think this will be all that hard... We just need the following:

- A method channel interface handler for creating a wake alarm
  * This should probably store some sort of Message GUID we can use to build a new notification for
- A handler and method channel interface for when the wake alarm is activated and "wakes" the app
  * The Message GUID mentioned above should be able to be pulled out (I think) and used to create a new notification
- A new action added to the New Message notification called `Mute 1h`
  * The intent will call the method channel interface mentioned above
- Add UI elements/actions to be able to temporarily mute a conversation
  * This probably can be done in the chat details page

**Comment by CSab6482** [comment] 2021-09-01 02:34
Is #813 a dupe of this?

**Comment by zlshames** [comment] 2021-09-01 02:43
> Is #813 a dupe of this?

Nah, 813 is more like having a "Remind 1 he" action next to reply and mark as reply in your notification

**Closed** 2021-09-01 03:44 UTC
Labels: Enhancement, UX, Difficulty: Hard, Difficulty: Medium
