### ISSUE TITLE
Delivered receipts still don't show sometimes

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#666] opened 2021-01-14 18:04 UTC
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#feedback`.

**Comment by zlshames** [comment] 2021-06-16 22:11
This is a dupe of this: https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/801
Closing

**Closed by zlshames** 2021-06-16 22:11 UTC
Labels: Bot Created, Bug
