### ISSUE TITLE
Add send sounds

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#811] opened 2021-03-08 17:08 UTC
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#general`.

**Comment by zlshames** [comment] 2021-06-15 20:59
This is just a matter of doing 3 things, but overall fairly easy. Marking this as `medium` because it touches on a few parts of the app:

- Adding an audio resource for the send sound
- Adding code here to play the sound: https://github.com/BlueBubblesApp/BlueBubbles-Android-App/blob/master/lib/layouts/conversation_view/conversation_view.dart#L130
- Adding a toggle to the settings (this should be off by default)

**Comment by zlshames** [comment] 2021-06-15 21:01
Duplicate of: https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/524

**Closed by zlshames** 2021-06-15 21:01 UTC
Labels: Backlog, Bot Created, Difficulty: Medium, Enhancement, good first issue
