### ISSUE TITLE
Opening a brand new chat from a notification doesn't work

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1205] opened 2021-07-27 20:06 UTC
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#support`.

**Comment by zlshames** [comment] 2021-07-28 16:59
From Slofiend:

```
The message came in to the notification panel and was missing in the app. I pulled down the notification and tapped it. The notification disappeared form the panel and I was taken to the app. I read the message and closed the app. I re-opened the app and the message was gone. I went into the Server Settings and manually synced the messages for 1 day. I see the message now in the app, I tap it, read the message, and close the app. I re-open the app and the message is gone. This time after doing the manual re-sync when I go into the message, I reply. The message/chat now remains in the app after closing and re-opening it. All works well with that workaround. The kicker is that you have to respond to the message or else it will continue to disappear from the app and require a manual resync.
```

**Comment by zlshames** [comment] 2021-08-02 21:08
Marking this as high priority because it is kinda a main-app functionality. Also marking as Medium because deleting and recreating chats will be required and it's a little tedious

**Comment by tneotia** [comment] 2021-08-03 02:14
Cannot reproduce, deleted a chat I had with myself, sent a message, and received and opened the notification successfully.

**Comment by zlshames** [comment] 2021-08-03 02:43
> Cannot reproduce, deleted a chat I had with myself, sent a message, and received and opened the notification successfully. We may need to grab logs from slofiend.

Did you delete the chat, then do a reset and resync, then get the notif? That'll give the best answer because I think when you delete a chat, there might be leftover artifacts if you don't? Also, delete the chat on your Mac too. 

I just wanna be thorough if this is actually an issue

**Comment by zlshames** [comment] 2021-08-04 18:57
Can't reproduce. Closing until it comes back up again. I think the bug was in a play store build. And we have not updated it in a fair bit. Probably fixed it already.

**Closed by zlshames** 2021-08-04 18:57 UTC
Labels: Bot Created, Bug, Difficulty: Medium, UX, priority: high
