### ISSUE TITLE
[Feature Request] iPad iMessage layout for Android tablets

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1335] opened 2021-08-08 18:27 UTC
Whether you're vertical or horizontal on an iPad, the chat list is always shown on the left, and this allows for useful features such as dragging and dropping an attachment into another chat to send it in there.

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#requests`.

**Comment by CSab6482** [comment] 2021-08-09 03:42
Dupe of #641 and #1210

**Closed** 2021-08-15 01:52 UTC
Labels: Bot Created
