### ISSUE TITLE
Group notifications into 1 icon

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#775] opened 2021-02-10 23:05 UTC
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#requests`.

**Comment by zlshames** [comment] 2021-06-15 21:30
I need some more information for this to proceed. Not sure what it needs to look like. I need an example

**Comment by CSab6482** [comment] 2021-06-17 01:08
Possible dupe of #212. And I think I know what they mean. Let's say I have notifications from three BlueBubbles chats. Sometimes, I have three separate BlueBubbles icons in my notification bar at the top, and other times, I only have one that then splits into the separate chats. At least I think that's what they mean.

**Comment by tneotia** [comment] 2021-08-05 03:08
Done

**Closed by tneotia** 2021-08-05 03:08 UTC
Labels: Bot Created, Enhancement, Needs More Info
